[package]
name = "iced_drop"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
iced_core = "0.14"
iced_widget = "0.14"
iced = { version = "0.14", optional = true }

[workspace]
members = ["examples/*"]

[features]
helpers = ["iced/advanced"]