[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", features = [
    "advanced",
    "lazy",
] }
iced_drop = { path = "../.." }
